### ISSUE TITLE
RuntimeError: MAD-X has stopped working!

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#16]
Hi, Thomas

When I run a simple example in pythonxy, an error occurs--RuntimeError: MAD-X has stopped working!

example:
```python
from cpymad.madx import Madx

# create a new interpreter instance:
# the optional 'command_log' parameter can be used to store MAD-X
# command history.
madx = Madx(command_log="log.madx")

# determine the version of MAD-X that is actually loaded:
print(madx.version) 

# you execute arbitrary textual MAD-X commands:
#madx.input('call, file="input_file.madx";')

# there is a more convenient syntax available which does the same:
madx.command.call(file="HITFIL.madx")

# And for some commands there exist direct shortcuts:
#madx.call('/path/to/some/input_file.madx')

#Calculate TWISS parameters
twiss = madx.twiss(sequence='RING', betx=0.1, bety=0.1, alfx=0.1, alfy=0.1)

#Your own analysis below
import matplotlib.pylab as plt
plt.plot(twiss['s'], twiss['betx'])
plt.show()
```

error:
```python
runfile('E:/cython_madx/test/cpymad/1.py', wdir='E:/cython_madx/test/cpymad')
MAD-X 5.02.04 (2014.11.14)
Traceback (most recent call last):

  File "<ipython-input-1-f4c790c83cb7>", line 1, in <module>
    runfile('E:/cython_madx/test/cpymad/1.py', wdir='E:/cython_madx/test/cpymad')

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 601, in runfile
    execfile(filename, namespace)

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 66, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "E:/cython_madx/test/cpymad/1.py", line 21, in <module>
    madx.command.call(file="HITFIL.madx")

  File "C:\Python27\lib\site-packages\cpymad\madx.py", line 88, in __call__
    self.__dispatch(util.mad_command(*args, **kwargs))

  File "C:\Python27\lib\site-packages\cpymad\madx.py", line 227, in input
    raise RuntimeError("MAD-X has stopped working!")

RuntimeError: MAD-X has stopped working!
```

**Comment by coldfix** [comment]
This usually occurs, because MAD-X is extremely buggy and might not be cpymad related at all. Did you check if your file works when used with plain MAD-X, i.e.:

```
madx_dev < HITFIL.madx
```

If this crashes too — don't ask me, ask the MAD-X folk.

Also: you didn't post `HITFIL.madx` which is exactly where the error happens (but only post minimal example!).

In the future, please provide all the necessary files so I can reproduce your error locally. If you want to be helped you should try to make it as easy as possible to help you. Don't require others to pull every piece of information out of you. It's not their job to try to guess what's on your mind. In general: be more thoughtful before asking others.

Please read [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and Eric Raymonds [How To Ask Questions The Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) before posting further issues.

**Comment by cpyman** [comment]
Hi, 

Sorry for this.

While commented the line, the program works well. Why?
```python
twiss = madx.twiss(sequence='RING', betx=0.1, bety=0.1, alfx=0.1, alfy=0.1)
```

another question:
How to plot 3 lines(e.g. betx, bety, dx) on a figure?

**Comment by coldfix** [comment]
Ok, obviously. You are just trying to troll me. If not, please read my last post.
