### ISSUE TITLE
How to use MADGUI

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#18]
Hi, Thomas

How to use MADGUI?

**Comment by coldfix** [comment]
Start program.

**Comment by cpyman** [comment]
Sorry. How to start?

```python
MadGUI
Traceback (most recent call last):

  File "<ipython-input-57-db3d73b00d0a>", line 1, in <module>
    MadGUI

NameError: name 'MadGUI' is not defined
```

```python
import MadGUI
Traceback (most recent call last):

  File "<ipython-input-59-79d0ef2bf2e5>", line 1, in <module>
    import MadGUI

ImportError: No module named MadGUI
```

**Comment by coldfix** [comment]
In your terminal type ``madgui`` or ``python -m madgui``

**Comment by cpyman** [comment]
![default](https://cloud.githubusercontent.com/assets/8341044/8253247/8e684f24-16c0-11e5-81a9-4be150f127b6.png)
The Chinese means ```Not such a command or not a executable program```

**Comment by coldfix** [comment]
Install madgui first.

**Comment by coldfix** [comment]
``python setup.py install``

**Comment by cpyman** [comment]
Yes, It works.

**Comment by coldfix** [comment]
I can't stress this enough: **Please be more specific!**, as I have already stated *many* times!

Your question "how to *use* Madgui" indicates, that you just don't know how to use it. But now it turns out, you don't even have it installed...

When asking a question, you have to make sure, your peer knows exactly
- what you did and didn't do
- what you want to do
- and **be specific**

Next issue like this, I will simply put you on ignore.

**Comment by cpyman** [comment]
OK
