### ISSUE TITLE
Cannot install on macos high sierra

### ISSUE THREAD

**Issue by piotrskowronski** [hibtc/cpymad#69]
MacOS High Sierra with MacPorts.

I issue this command to install
 sudo -H pip-3.8 install cpymad  --only-binary " "

 and get this error   

 /usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names build/temp.macosx-10.13-x86_64-3.8/src/cpymad/libmadx.o -lmadx -lDISTlib -lptc -lgc-lib -lstdc++ -lgfortran -lquadmath -o build/lib.macosx-10.13-x86_64-3.8/cpymad/libmadx.cpython-38-darwin.so
    ld: library not found for -lDISTlib

[out.txt](https://github.com/hibtc/cpymad/files/5324126/out.txt)

**Comment by coldfix** [comment]
Hi,

thanks for the issue report!

We currently don't have prebuilt binaries for Mac, because I don't have any experience that platform, so it's not a surprise that this doesn't install as is.

Since ld seems to find the `madx` library, but not `DISTlib`, this hints that it found either

1. a version of madx older than 5.06.00, or
2. a shared-library build of madx (which has distlib integrated).

In the first case, try building this with the newest version of MAD-X. Commands should be similar to the [Unix Installation](https://hibtc.github.io/cpymad/installation/unix.html).

In the second case, it might be enough to `export SHARED=1` in the environment before running pip.

If you manage to make this work, it would be great if you could give us a few hints as to further problems / differences to the unix workflow.

Best, Thomas

**Comment by piotrskowronski** [comment]
Hi,

It does not work. I think you need to include in your wheel libDISTlib.dylib.

What I did exactly
macbe16187:dist skowron$ pwd
/Users/skowron/Downloads/dist
macbe16187:dist skowron$ ls -1
cpymad-1.6.1-cp27-cp27m-macosx_10_14_x86_64.whl
cpymad-1.6.1-cp35-cp35m-macosx_10_14_x86_64.whl
cpymad-1.6.1-cp36-cp36m-macosx_10_14_x86_64.whl
cpymad-1.6.1-cp37-cp37m-macosx_10_14_x86_64.whl
cpymad-1.6.1-cp38-cp38-macosx_10_14_x86_64.whl
cpymad-1.6.1.tar.gz
macbe16187:dist skowron$ pip-3.7 install cpymad -f /Users/skowron/Downloads/dist
...
...
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/cpymad/libmadx.c -o build/temp.macosx-10.13-x86_64-3.7/src/cpymad/libmadx.o -std=gnu99
  /usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names build/temp.macosx-10.13-x86_64-3.7/src/cpymad/libmadx.o -lmadx -lDISTlib -lptc -lgc-lib -lstdc++ -lgfortran -lquadmath -o build/lib.macosx-10.13-x86_64-3.7/cpymad/libmadx.cpython-37m-darwin.so
  ld: library not found for -lDISTlib

**Comment by coldfix** [comment]
> I think you need to include in your wheel libDISTlib.dylib.

The error is a build error that is likely to one of the above mentioned issues. Its occurence indicates that pip couldn't find a usable binary wheel and tried to build from source instead - which I I guess answers my first question in #70:

> The wheels are named after OS version on which they were built (macos 10.14). Do you happen to know, how older versions 10.X will deal with these wheels, i.e. will they accept to install them and work?

I would guess that your pip on macos 10.13 doesn't want to pick up the wheel because it is tagged with 10.14 (?).

To make sure, could try the following with the previously downloaded wheels and *updated pip* (!):

```
python-3.7 -m venv env
source env/bin/activate
pip install --upgrade pip

pip install dist/cpymad-1.6.1-cp37-cp37m-macosx_10_14_x86_64.whl
```

If you get an error like `[...] is not a supported wheel on this platform.`, can you try it with [these wheels](https://github.com/hibtc/cpymad/suites/1303860675/artifacts/20496721) instead:

```
pip install FOLDER/cpymad-1.6.1-cp37-cp37m-macosx_10_9_x86_64.whl
python -c 'import cpymad.libmadx as l; l.start()'
```

These wheels were built by manually setting an older platform tag. If this fails, I may have to try to get hold of an older macos version to build on.

Thanks for your patience!

**Comment by coldfix** [comment]
You can probably ignore the instructions from my previous comment. Those will have a very low chance of success.

Try installing from [this build of wheels](https://github.com/hibtc/cpymad/suites/1304835754/artifacts/20524202) instead, e.g.:

```
pip install FOLDER/cpymad-1.6.1-cp37-cp37m-macosx_10_9_x86_64.whl
python -c 'import cpymad.libmadx as l; l.start()'
```

**Comment by piotrskowronski** [comment]
Hi,

I finally managed, but this is a hack working around flaws of MADX cmake.

```
mkdir /tmp/b
cd /tmp/b
cmake -L -DUSE_GC=0  -DMADX_STATIC=ON     -DMADX_ONLINE=OFF     -DBUILD_SHARED_LIBS=OFF     -DCMAKE_INSTALL_PREFIX=$MADXDIR     -DCMAKE_C_FLAGS="-fvisibility=hidden"     -DCMAKE_BUILD_TYPE=Release     -DMADX_INSTALL_DOC=OFF  $MADXDIR
make
```
make stops with error when linking madx program, but earlier it manages to compile and link the libraries.
I copy manually the compiled libs to $MADXDIR.

Than your wheel provided above works no problem.

Clearly the issue is MADX's cmake configuration that does not work for my platform.

**Comment by coldfix** [comment]
Just to clarify:

the *wheels* are fully built binary distributions that should work for users without ever touching MAD-X source or cmake.

Did you try installing a wheel from the my latest comment? (`pip install cpymad-XXX.whl`) It does work in testing for systems that don't have MAD-X source, and it has a a platform tag that should be compatible with yours.

**Comment by fsoubelet** [comment]
Hi @coldfix, just chiming in to notify you that installing from the recently built wheels has worked fine for me on macOS 10.15.6 👍

**Comment by coldfix** [comment]
@fsoubelet Great thanks for the info. I will make a release including mac wheels soon. One question maybe you know more about: Is the accelerate framework available on every mac, or does the user have to install it manually?

**Comment by fsoubelet** [comment]
Hi again, unfortunately I wouldn't be able to tell you that.
