### ISSUE TITLE
The ";" in the log file 

### ISSUE THREAD

**Issue by sterbini** [hibtc/cpymad#73]
Hi, 
I am running this simple code
```python
from cpymad.madx import Madx 
mad = Madx(command_log="my_log.log")
mad.input('a=1')
mad.input('value, a')
mad.value('a')
```
if I see the "my_log.log" I get

```
a=1
value, a
value, a;
```
so if I try to run the "my_log.log" directly with **madx**
```
madx my_log.log
```

I cannot retrieve the same result behaviour I get with cpymad (due to the two missing ";"). Is this a wanted feature? I would suggest forcing the ";" also on the "my_log.log" to make it a working **madx** input.

Thanks.

**Comment by coldfix** [comment]
Hi,

you're right, we should add the `;` to the command log as well since it is also implicitly added to the MAD-X input. This will be done in the next version. For now, just manually append `;` whenever calling `input()` manually, e.g.:

```python
from cpymad.madx import Madx 
mad = Madx(command_log="my_log.log")
mad.input('a=1;')
mad.input('value, a;')
```

Historically, `input()` is a rather low level method (still is), that didn't automatically append `;` if it was missing. The user was fully responsible to correctly fill in all `;` to commands entered via `input()`. Only recently (`v1.0.6`) the behaviour was changed to always add an implicit `;` at the very end of every `input()` because it was too easy to forget if composing commands manually. However, as you see, I forgot to also add it to `command_log`.

**Comment by sterbini** [comment]
Thanks!
