### ISSUE TITLE
Issues with nested sequences

### ISSUE THREAD

**Issue by Oskari-Tuormaa** [hibtc/cpymad#76]
I've run into an error saying that sub-sequences are empty when in reality they're not. I've included the following minimal example for which I get the error:

```python
import cpymad.madx as madx

mad = madx.Madx()
mad.input("""
d1: RBEND, l=0.1, angle=0.1;

seq1: sequence, l=0.1;
    d1.1: d1, at=0.05;
endsequence;

seq2: sequence, l=0.2;
    seq1, at=0.05;
    seq1, at=0.15;
endsequence;
""")
mad.sequence["seq2"].elements["seq1"]
```

Upon running this example, I get the following output:

```
RuntimeError: Traceback (most recent call last):
  File "/home/oskari/.local/lib/python3.7/site-packages/minrpc/service.py", line 85, in _dispatch
    response = handler(*args)
  File "/home/oskari/.local/lib/python3.7/site-packages/minrpc/service.py", line 103, in _dispatch_function_call
    return function(*args, **kwargs)
  File "src/cpymad/libmadx.pyx", line 592, in cpymad.libmadx.get_element
  File "src/cpymad/libmadx.pyx", line 1154, in cpymad.libmadx._get_node
RuntimeError: Empty node or subsequence! Please report this incident!
```

**Comment by ydutheil** [comment]
Hi,

I see indeed that does not work. 
I personally never ran into that issue, possibly because I always flatten my sequences.

Also, note that by default RBEND length is the magnet length while MADX sequence has the length of the arc, which is the reference trajectory. Therefore the element `d1.1` has a reference length > 0.1 m and MADX crashes when trying to expand that sequence. MADX also wants a beam. 

Please see the example below, I always expand my sequences there. 

```python
import cpymad.madx as madx

mad = madx.Madx()
mad.input("""
beam, pc=1;
d1: SBEND, l=0.1, angle=0.1;

seq1: sequence, l=0.1;
    d1.1: d1, at=0.05;
endsequence;


seq2: sequence, l=0.2;
    seq1, at=0.05;
    seq1, at=0.15;
endsequence;
""")
mad.sequence["seq2"].elements
mad.input('seqedit, sequence=seq2; flatten; endedit;')
mad.sequence["seq2"].elements

mad.use('seq2')
mad.twiss(betx=1, bety=1).dframe(columns=['keyword', 'l', 's', 'angle'])
```

Now, I did not answer your question but looking at cpymad, the `sequence.elements` is an `ElementList` object. I stopped there but I will try and look some more if no one else knows the answer.

**Comment by coldfix** [comment]
Hi,

I think cpymad currently only works with flattened sequences, which I think happens automatically once the sequence is used, i.e., all you have to do would be to `use, sequence=seq2;` before touching it in cpymad.

To support nested sequences, some changes might be necessary. I probably won't work on that, so patches welcome.

**Comment by coldfix** [comment]
If anyone wants to work on this, implement the `if`-branch in `src/cpymad/libmadx.pyx:1152` in the `_get_node` function where the error originated, and patch `ElementList._get_element` and `ElementList._get_element_at` to return a `Sequence` object in that case.

**Comment by coldfix** [comment]
I've added basic support for nested sequences. Such nodes should now yield a `Sequence` object. I didn't invest any time in making sure this plays together with all program parts, so let me know if you run into further problems.
