### ISSUE TITLE
Problem with cpymad in Linux

### ISSUE THREAD

**Issue by tpersson** [hibtc/cpymad#79]
It works fine to compile and I can run the setup without any problem but I can't run it afterwards. The same problem actually happens also in the GitHub action. I tried to re-run an old run that before was working but now it also fails and the error is the same as I get locally. Anyone has any idea what this could be?

https://github.com/MethodicalAcceleratorDesign/MAD-X/runs/2022689777?check_suite_focus=true

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/minrpc/client.py", line 61, in __del__
    self.close()
  File "/home/runner/work/MAD-X/MAD-X/src/cpymad/_rpc.py", line 53, in close
    if self.libmadx.is_started():
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/minrpc/client.py", line 159, in DeferredMethod
    return self.__client._request('function_call', self.__module,
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/minrpc/client.py", line 112, in _request
    return self._dispatch(response)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/minrpc/client.py", line 123, in _dispatch
    return handler(*args)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/minrpc/client.py", line 129, in _dispatch_exception
    raise type(exc_type.__name__, (exc_type,), {
minrpc.client.ImportError: Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/minrpc/service.py", line 85, in _dispatch
    response = handler(*args)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/minrpc/service.py", line 101, in _dispatch_function_call
    module = __import__(modname, None, None, '*')
ImportError: /home/runner/work/MAD-X/MAD-X/src/cpymad/libmadx.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2vv_pow

**Comment by coldfix** [comment]
Hi, apparently cpymad was linked against a dynamic symbol that is unavailable at run time. This typically happens if the compiler knows about some library that the system runtime doesn't know about, e.g. due to environment variables, or if the program is executed on a different OS than it was built on, that has a different CRT, or it was built with lapack, but that is not installed on the runtime machine.


Does this happen with the cpymad binary installed using `pip install cpymad`? According to  `nm -D <file>` or `objdump -T` that symbol is not loaded neither by libmadx.so nor the shipped libgfortran.so, so it should not be the case for this build.

**Comment by tpersson** [comment]
Thanks for the quick reply! In case I install it using pip install cpymad then it works fine for me the problem is really when I try to install my own compiled version and when we are running the tests on GitHub actions.. I am a but confused because it used to work and it is not clear to me what has changed..

**Comment by coldfix** [comment]
Possibly due to a change in compiler or library versions in the github actions environment. I'm looking into it and will hopefully post a PR soon (also for the other issue mentioned two weeks ago).

**Comment by coldfix** [comment]
FYI: it's probably due to "ubuntu-latest" being changed from meaning "ubuntu-16.04" to "ubuntu-20.04". This change is already in effect these builds.

**Comment by coldfix** [comment]
Ok, I have now identified the problem. It is due to the new gcc version on the updated OS employing vectorization in release builds. There are several fixes:

- tell cpymad to link against `-libmvec`, this happens automatically if passing `-lm` and can be passed through `python setup.py build_ext -lm`.
- build madx without vector optimizations (`-DCMAKE_C_FLAGS="-fno-tree-vectorize"` etc). These optimizations are also disabled in debug mode by default.
- build madx as shared object: set `-DBUILD_SHARED_LIBS=ON` in cmake and run `setup.py` with `export SHARED=1`. In this case cmake links all dependencies including `-lm` correctly to the madx shared object so one doesn't need to know during the cpymad build

The best fix for local use is probably the first option.

I will have to checkout whether the `-lm` flag can safely be added in `setup.py` (i.e. even for the manylinux build) or whether that could lead to other problems due to missing libraries/symbols when deploying to a different system.

**Comment by rdemaria** [comment]
sorry to reopen, I have the same issue while compiling locally.

`python setup.py build_ext -lm` does not help in my case, I try the other options...

**Comment by coldfix** [comment]
Is it the same error message? Is this on MacOS? Also try `-lmvec`.

**Comment by rdemaria** [comment]
same error, I am on linux (arch derivative)

**Comment by coldfix** [comment]
I'm on archlinux as well. `-lm` works for me, but you have to remove the `build` directory and/or .so existing .so files first to force a rebuild:

```
rm -r build src/cpymad/*.so
```

**Comment by coldfix** [comment]
Yes, `-DMADX_STATIC=OFF` doesn't work on archlinux because it doesn't ship libgfortran.a, but that is not important for local builds anyway (it's mainly useful for deploying binaries without dependencies).

If building with `-DBUILD_SHARED_LIBS=ON` you also have to specify `export SHARED=1` during the cpymad build, and take care that the `libmadx.so` can be found at runtime.

**Comment by rdemaria** [comment]
Yes, I always delete the .so!  My problem with `-DBUILD_SHARED_LIBS=ON` is that madx does not compile

**Comment by coldfix** [comment]
>  My problem with `-DBUILD_SHARED_LIBS=ON` is that madx does not compile

Oh sorry, I misread your earlier message. I've seen and I believe fixed these build errors before... hmm let me think about it and get back to you tomorrow or so. However, I would generally not recommend building MAD-X as shared object anyway. It's more important to fix the "undefined symbol" error.

**Comment by coldfix** [comment]
> Yes, I always delete the .so!

Ok. In that case, did you also `pip uninstall cpymad; pip install -e .` to make sure that the newly built .so is also the one that is imported?

If that is the case, what is the output of `ldd src/cpymad/libmadx*.so` and `nm src/cpymad/libmadx*.so | grep _ZGVbN2vv`?

**Comment by coldfix** [comment]
>     1. Arch does not ship static libraries by default (if I knew I would not have installed it) therefore I tried to compile libmadx with
>        ` -DMADX_STATIC=OFF -DBUILD_SHARED_LIBS=ON`  but then I get
> 
> 
> `` ...ld: CMakeFiles/madxbin.dir/mad_main.c.o: in function `main': mad_main.c:(.text.startup+0x26): undefined reference to `madx_start' ... `` and similarly for `madx_input madx_finish ...` and so on

Ah, FYI, I remembered, if you're building with `-DCMAKE_C_FLAGS="-fvisibility=hidden"` that's the reason. It should work without this option or by changing hidden to protected. See also the paragraph on shared linking in the [cpymad documentation](http://hibtc.github.io/cpymad/installation/unix.html#id1).

**Comment by rdemaria** [comment]
Thanks for pointing to the documentation, I missed this part! I think I must have missed the uninstall part in some of the test. Now -lm works for me. I will try the shared recipe, but I think the present setup is ok for me! Thanks again!

**Comment by coldfix** [comment]
Ok great! Then I'll close again. I have now also added the solutions from this thread to the [Troubleshooting](http://hibtc.github.io/cpymad/installation/troubleshooting.html) page.
