### ISSUE TITLE
Giving cpymad a DOI

### ISSUE THREAD

**Issue by fsoubelet** [hibtc/cpymad#84]
Hi Thomas,

I use `cpymad` extensively and would be happy to give it a proper citation.

The standard way to do this for softwares that don't have an explicit paper publication dedicated to them is to get them a DOI through [Zenodo](https://zenodo.org/). The process is very simple and straightforward, here is a small [tutorial](https://guides.github.com/activities/citable-code/) by Github.

Do you think `cpymad` would be open to getting a DOI?

**Comment by coldfix** [comment]
Hey,

sounds like a good idea. Thanks for the links! I'll try to make it work :)

FYI, there is a paper on a very early version of the original pymad (from which this project was forked): http://www-linac.kek.jp/mirror/IPAC2011/papers/wepc119.pdf, but I'll create a a new DOI anyway, since this project is very different now.
